version: '3'
services:
    frontend_dev:
        build:
            context: ./ /../../../
            dockerfile: ./docker/dev/Dockerfile
        environment:
            - PORT=3000
            - NODE_ENV=production
            - APP_ENV=dev
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        ports:
            - 3000:3000