version: '3'
services:
    frontend_stage:
        build:
            context: ./ /../../../
            dockerfile: ./docker/stage/Dockerfile
        environment:
            - PORT=3000
            - NODE_ENV=production
            - APP_ENV=stage
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        ports:
            - 3000:3000